# Generated by Django 5.2.7 on 2025-10-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_attachment'),
        ('app', '0003_add_attachment'),
    ]

    operations = [
    ]
